In [1]:
%load_ext autoreload
%autoreload 2



In [2]:
import jax
import jax.numpy as jnp
import cvxpy as cp
from cvxpylayers.jax import CvxpyLayer

In [3]:
cost = cp.Parameter((1, 3), nonneg=True)
x = cp.Variable((3,1))
A = cp.Parameter((4, 3))
b = cp.Parameter((4, 1))
objective = cp.Minimize(cost @ x)
constraints = [A @ x <= b, x >= 0]

In [4]:
c_p, A_p, b_p  = jnp.array([1., 2., 3.]).reshape(1, -1), jnp.array([[-1., -1., 0.], [1., 1., 0.], [-1., 0., -1.], [1., 0., 1.]]), jnp.array([-2., 3., -4., 5.]).reshape(-1,1)

In [5]:
problem = cp.Problem(objective, constraints)

In [6]:
cvxpylayer = CvxpyLayer(problem, [cost, A, b], variables=[x])

In [7]:
A.value

In [8]:
solution, = cvxpylayer(c_p, A_p, b_p)

In [9]:
A.value

In [10]:
solution

DeviceArray([[ 2.9999990e+00],
             [-2.6778071e-07],
             [ 9.9999875e-01]], dtype=float32)

In [11]:
constraints

[Inequality(Expression(AFFINE, UNKNOWN, (4, 1))),
 Inequality(Constant(CONSTANT, ZERO, ()))]

In [12]:
# Solve using cvxpy to get dual values of constraints
A.value, b.value, cost.value = A_p.to_py(), b_p.to_py(), c_p.to_py()

In [13]:
problem.solve()

5.999999998668912

In [14]:
constraints[0].dual_value

array([[8.75693352e-10],
       [2.00000000e+00],
       [3.00000000e+00],
       [1.14542311e-09]])

In [15]:
constraints[1].dual_value

array([[6.09314939e-10],
       [4.00000000e+00],
       [2.56363292e-10]])

In [16]:
x.value

array([[ 3.00000000e+00],
       [-3.04813787e-10],
       [ 1.00000000e+00]])